
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b"mQS48\x87'\xc6\x8c\xfe5\xa47\xad\x91\xd8"
    
_lr_action_items = {'NAME':([1,2,4,8,9,],[4,6,8,9,10,]),'FUNC':([0,],[1,]),'RET':([0,],[2,]),'$end':([2,3,4,5,6,7,8,9,10,],[-5,0,-1,-6,-14,-15,-2,-3,-4,]),'NUMBER':([2,],[7,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([2,],[5,]),'func':([0,],[3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> func","S'",1,None,None,None),
  ('func -> FUNC NAME','func',2,'p_func_start','C:\\Users\\DylanBrophy\\Desktop\\osdev\\OSD.py',60),
  ('func -> FUNC NAME NAME','func',3,'p_func_start','C:\\Users\\DylanBrophy\\Desktop\\osdev\\OSD.py',61),
  ('func -> FUNC NAME NAME NAME','func',4,'p_func_start','C:\\Users\\DylanBrophy\\Desktop\\osdev\\OSD.py',62),
  ('func -> FUNC NAME NAME NAME NAME','func',5,'p_func_start','C:\\Users\\DylanBrophy\\Desktop\\osdev\\OSD.py',63),
  ('func -> RET','func',1,'p_func_end','C:\\Users\\DylanBrophy\\Desktop\\osdev\\OSD.py',80),
  ('func -> RET expression','func',2,'p_func_end','C:\\Users\\DylanBrophy\\Desktop\\osdev\\OSD.py',81),
  ('raw -> INTT NAME','raw',2,'p_raw_set','C:\\Users\\DylanBrophy\\Desktop\\osdev\\OSD.py',87),
  ('raw -> INTT NAME EQU expression','raw',4,'p_raw_set','C:\\Users\\DylanBrophy\\Desktop\\osdev\\OSD.py',88),
  ('raw -> FLOATT NAME','raw',2,'p_raw_set','C:\\Users\\DylanBrophy\\Desktop\\osdev\\OSD.py',89),
  ('raw -> FLOATT NAME EQU expression','raw',4,'p_raw_set','C:\\Users\\DylanBrophy\\Desktop\\osdev\\OSD.py',90),
  ('raw -> STRT NAME EQU STR','raw',4,'p_raw_set','C:\\Users\\DylanBrophy\\Desktop\\osdev\\OSD.py',91),
  ('raw -> POINT NAME EQU NUMBER','raw',4,'p_raw_set','C:\\Users\\DylanBrophy\\Desktop\\osdev\\OSD.py',92),
  ('register -> REGISTER EQU expression','register',3,'p_register_set','C:\\Users\\DylanBrophy\\Desktop\\osdev\\OSD.py',108),
  ('expression -> NAME','expression',1,'p_expression_var','C:\\Users\\DylanBrophy\\Desktop\\osdev\\OSD.py',111),
  ('expression -> NUMBER','expression',1,'p_expression_int','C:\\Users\\DylanBrophy\\Desktop\\osdev\\OSD.py',118),
]
